app:
  config-host: localhost:3964

server:
  port: 3743

spring:
  application:
    name: server-eureka
  config:
    import: optional:configserver:http://${app.config-host}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false