app:
  config-server:
    url: http://localhost:3964
  eureka:
    url: http://localhost:3743/eureka/

server:
  port: 925

spring:
  application:
    name: service-post
  config:
    import: optional:configserver:${app.config-server.url}
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

eureka:
  client:
    service-url:
      defaultZone: ${app.eureka.url}