app:
  server-config:
    url: http://localhost:3964
  server-eureka:
    url: http://localhost:3743/eureka/

server:
  port: 5153

spring:
  application:
    name: server-gateway
  cloud:
    gateway:
      routes:
        - id: service-chat
          uri: lb://service-chat
          predicates:
            - Path=/api/chat/**
          filters:
            - JwtAuthFilter
            - RewritePath=/api/chat(?<segment>.*),${segment}

        - id: service-post
          uri: lb://service-post
          predicates:
            - Path=/api/post/**
          filters:
            - JwtAuthFilter
            - RewritePath=/api/post(?<segment>.*),${segment}

        - id: service-recipe
          uri: lb://service-recipe
          predicates:
            - Path=/api/recipe/**
          filters:
            - JwtAuthFilter
            - RewritePath=/api/recipe(?<segment>.*),${segment}

        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/user/**
          filters:
            - JwtAuthFilter
            - RewritePath=/api/user(?<segment>.*),${segment}
  config:
    import: optional:configserver:${app.server-config.url}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${app.server-eureka.url}

management:
  endpoints:
    web:
      exposure:
        include: "*"