app:
  config-host: localhost:3964
  eureka-host: localhost:3743

server:
  port: 4338

spring:
  application:
    name: service-recipe
  config:
    import: optional:configserver:http://${app.config-host}
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-host}/eureka/