app:
  server-config:
    url: http://localhost:3964
  server-eureka:
    url: http://localhost:3743/eureka/

server:
  port: 7234

spring:
  application:
    name: service-user
  config:
    import: optional:configserver:${app.server-config.url}
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

eureka:
  client:
    service-url:
      defaultZone: ${app.server-eureka.url}