server:
  port: 1085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: service-chat
          uri: lb://service-chat
          predicates:
            - Path=/api/chats/**
          filters:
            - RewritePath=/api/chats(?<segment>.*),${segment}

        - id: service-post
          uri: lb://service-post
          predicates:
            - Path=/api/posts/**
          filters:
            - RewritePath=/api/posts(?<segment>.*),${segment}

        - id: service-recipe
          uri: lb://service-recipe
          predicates:
            - Path=/api/recipes/**
          filters:
            - RewritePath=/api/recipes(?<segment>.*),${segment}

        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/users/**
          filters:
#            - RewritePath=/api/users(?<segment>.*),${segment}
            - AddRequestHeader=X-Forwarded-Host, localhost:1085
            - AddRequestHeader=X-Forwarded-Proto, http

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:3743/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"