server:
  port: 3615

spring:
  application:
    name: service-chat
  config:
    import: optional:configserver:http://localhost:3964

eureka:
  client:
    service-url:
      defaultZone: http://localhost:3743/eureka/