app:
  server-config:
    url: http://localhost:3964
  server-eureka:
    url: http://localhost:3743/eureka/

server:
  port: 3615

spring:
  application:
    name: service-chat
  config:
    import: optional:configserver:${app.server-config.url}
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000

eureka:
  client:
    service-url:
      defaultZone: ${app.server-eureka.url}

logging:
  config: classpath:log4j2/log4j2-${spring.profiles.active}.properties